### ISSUE TITLE
Text limit error?

### ISSUE THREAD

**Issue by Colddeadhands** [Sqline/Sqline#13]
I'm attempting to convert a 180mb mysql create-table query into Oracle, and SQLinesw just chokes on the file and shuts down. I understand not being able to parse something that massive, but I'd hope for an error message that's more descriptive than 'contact the developer'.

**Comment by sguft** [comment]
Hi Colddeadhands

I believe you may have posted this in the wrong project - this project is a DataAccess Framework for .NET, not a database conversion tool.

Could this perhaps be what you are looking for?
https://github.com/julianhyde/sqlline

Cheers,
Daniel

**Comment by Colddeadhands** [comment]
Apologies! You're absolutely right.
